@echo off
set Sign="%~dp0..\Common\Signing\signing_user.bat"

call %Sign% "%~dp0Bin/x64/SbieRelease/KmdUtil.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SandboxieBITS.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SandboxieCrypto.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SandboxieDcomLaunch.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SandboxieRpcSs.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SandboxieWUAU.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SbieCtrl.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SbieIni.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SbieSvc.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/Start.exe"
call %Sign% "%~dp0Bin/x64/SbieRelease/SbieDll.dll"
call %Sign% "%~dp0Bin/x64/SbieRelease/SbieMsg.dll"
call %Sign% "%~dp0Bin/x64/SbieRelease/SboxHostDll.dll"

call %Sign% "%~dp0Bin/Win32/SbieRelease/KmdUtil.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SandboxieBITS.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SandboxieCrypto.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SandboxieDcomLaunch.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SandboxieRpcSs.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SandboxieWUAU.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SbieCtrl.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SbieIni.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SbieSvc.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/Start.exe"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SbieDll.dll"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SbieMsg.dll"
call %Sign% "%~dp0Bin/Win32/SbieRelease/SboxHostDll.dll"
REM ==================================================